package com.trustledger.core.model;

public enum LedgerTransactionType {
    INTERNAL_TRANSFER,EXTERNAL_TRANSFER_OUT,EXTERNAL_TRANSFER_IN,RESERVATION,RESERVATION_RELEASE,FEE,REFUND,REVERSAL,CHARGEBACK,MANUAL_ADJUSTMENT,SETTLEMENT,RECONCILIATION_ADJUSTMENT
}
