package com.trustledger.core.model;

public enum TransactionStatus {
    CREATED,VALIDATED,FRAUD_CHECK_PENDING,MFA_REQUIRED,HELD_FOR_REVIEW,FUNDS_RESERVED,POSTED,COMPLETED,REJECTED,FAILED,CANCELLED,REVERSED,PENDING_UNKNOWN
}
